# Generated by Django 5.2.7 on 2025-12-17 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hourly_Price', models.DecimalField(decimal_places=2, default='0.01', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('Experience', models.CharField(help_text='1 Year,3 Month', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Helper/Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.profile')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
            ],
            options={
                'verbose_name': 'Helper Service',
                'ordering': ['is_available'],
            },
        ),
    ]
