# Generated by Django 5.2.7 on 2025-12-17 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelperServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperservice',
            name='Hourly_Price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
