# Generated by Django 5.2.7 on 2025-12-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelperServices', '0002_alter_helperservice_hourly_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helperservice',
            name='Helper/Profile',
        ),
    ]
