# Generated by Django 5.2.7 on 2025-12-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelperServices', '0003_remove_helperservice_helper_profile'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperservice',
            name='Helper/Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Profile.profile'),
            preserve_default=False,
        ),
    ]
