# Generated by Django 5.2.7 on 2025-12-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelperServices', '0004_helperservice_helper_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helperservice',
            old_name='Experience',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='helperservice',
            old_name='Helper/Profile',
            new_name='helper',
        ),
        migrations.RenameField(
            model_name='helperservice',
            old_name='Hourly_Price',
            new_name='hourly_price',
        ),
        migrations.RenameField(
            model_name='helperservice',
            old_name='Service',
            new_name='service',
        ),
    ]
