# Generated by Django 5.2.7 on 2025-12-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelperServices', '0005_rename_experience_helperservice_experience_and_more'),
        ('Profile', '0001_initial'),
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='helperservice',
            unique_together={('helper', 'service')},
        ),
    ]
