# Generated by Django 5.2.7 on 2025-11-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Helper', 'HELPER'), ('Customer', 'CUSTOMER')], default='Customer'),
        ),
    ]
