# Generated by Django 5.2.7 on 2025-11-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Helper', 'HELPER'), ('Customer', 'CUSTOMER')], default='Customer', max_length=15),
        ),
    ]
