# Generated by Django 5.2.7 on 2025-12-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Hire.hire')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
